### ISSUE TITLE
Update pgns.json

### ISSUE THREAD

**Issue by fabdrol** [canboat/canboatjs#123]
`pgns.json` is out-of-date with canboat

**Comment by sbender9** [comment]
I just published a new version

**Comment by fabdrol** [comment]
of canboatjs?

**Comment by sbender9** [comment]
@canboat/pgns (1.3.2)

**Comment by fabdrol** [comment]
Yes, but is the version in `canboatjs` is old: https://github.com/canboat/canboatjs/blob/master/package.json#L52

**Comment by fabdrol** [comment]
Maybe I was unclear, but that was what my issue was about ;)

**Comment by sbender9** [comment]
You'll still get the latest because of the ^

**Comment by fabdrol** [comment]
of course, my mistake. thanks.
