### ISSUE TITLE
Fast Packets that are a single frame in length are not parsed as fast packets and thus use the first two bytes as PGN data

### ISSUE THREAD

**Issue by nmbath** [canboat/canboatjs#161]
It would seem that within fromPGN.js and the _parse function the logic for processing fast packets that are a single frame and therefore less than 6 bytes in length is wrong.

Within canboat the definition for PGN127507 is incorrect, it is defined as a single, when it is ineffective a fast. Having modified pgns.json to make it a fast, candumpanalyzerjs still will not process the PGN correctly. It processes it as a single. 

I have done some analysis and it seems to be within the _parse function. There are what looks like historic if statements commented out  related to " pgnData.Type === 'Fast' "

https://github.com/canboat/canboat/issues/243

**Comment by nmbath** [comment]
Test Can message....

 can0  19F21381   [8]  A0 06 71 00 08 FC FF FF

When I process PGN127507 with a correct definition:

        "PGN":127507,
        "Id":"chargerStatus",
        "Description":"Charger Status",
        "Type":"Fast",
        "Complete":true,
        "Length":6,
        "RepeatingFields":0,
        "Fields":[

I get

{"canId":435295105,"prio":6,"src":129,"dst":255,"pgn":127507,"timestamp":"2021-07-30T16:52:20.318Z","fields":{"Instance":160,"Battery Instance":6,"Operating State":"Bulk","Charge Mode":7,"Charger Enabled":"Off","Equalization Pending":"Off","Reserved1":"0","Equalization Time Remaining":64520},"description":"Charger Status"}

if I push the Length out to 9, I get a correct output...

{"canId":435295105,"prio":6,"src":129,"dst":255,"pgn":127507,"timestamp":"2021-07-30T16:48:59.722Z","input":[],"fields":{"Instance":113,"Battery Instance":0,"Operating State":"Disabled","Charge Mode":"Standalone mode","Charger Enabled":"Off"},"description":"Charger Status"}

A further example to show that there is an issue is this Actisense decode


![](https://user-images.githubusercontent.com/73959588/125491525-ba059074-0fb7-4347-9e60-8325377c3f21.png)

**Comment by anhorbc** [comment]
Any updates on this? I really wish for this to be fixed.

**Comment by sbender9** [comment]
@nmbath this is fixed, right?

**Comment by nmbath** [comment]
Yes I believe so. If further issues arise we can always re-open or create a new issue. Happy for it to be closed.

**Comment by sbender9** [comment]
Fix published today in 1.22.0
