### ISSUE TITLE
Incorrect instances being generated for PGN 127497

### ISSUE THREAD

**Issue by anhorbc** [canboat/canboatjs#185]
I was hoping that #162 would solve this, but apparently not. 
Attached is a can debug log.
[](url)
![image](https://user-images.githubusercontent.com/60405237/156409294-388bbe03-0dfe-42a3-b3d4-f571a1988389.png)
[skserver-raw_2022-03-02T17.zip](https://github.com/canboat/canboatjs/files/8171399/skserver-raw_2022-03-02T17.zip)

**Comment by sbender9** [comment]
These look like bad/malformed packets to me. I should be just ignoring them.

**Comment by sbender9** [comment]
which hardware device are you using to interface to n2k?

**Comment by anhorbc** [comment]
Sailor hat. (MCP2515 controller & ISO1050DUB isolated transceiver)

**Comment by sbender9** [comment]
Note there definitely seems to be some corruption:

```
1646237338450;A;2022-03-02T16:08:58.450Z,0,0,4,0,8,00,01,00,00,00,00,00,00
1646237338496;A;2022-03-02T16:08:58.451Z,5,127497,4,255,8,61,7f,ff,7f,ff,ff,ff,ff
```

**Comment by sbender9** [comment]
@mairas have you seen anything like this?
