### ISSUE TITLE
SignalK Port disconnection issue

### ISSUE THREAD

**Issue by Kashmala1** [canboat/canboatjs#196]
In SignalK configurations we are facing issue that the port we selected sometimes connected and sometimes it's disconnected automatically. What could be the reason for this? How can we resolve this issue? Can anyone please guide?

![image](https://user-images.githubusercontent.com/110451349/182314937-20bc2540-8ca6-4478-a534-b000dc265333.png)
![image](https://user-images.githubusercontent.com/110451349/182314979-e22bfe02-f524-4fba-9fd3-edad4b37698d.png)

**Comment by sbender9** [comment]
I think this is fixed, Please re-open if not.
