### ISSUE TITLE
YDWG typo

### ISSUE THREAD

**Issue by mairas** [canboat/canboatjs#197]
When investigating YDWG-02 UDP data connections in Signal K, I noticed that the YDWG-02 device and protocol name is mostly wrong (YDGW instead of YDWG). 

I was already creating a mass rename PR when I noticed that a partial rename _in the wrong direction_ had already been made in PR #59.

Before finishing my rename PR, I'd like to verify that this is a desired approach.

**Comment by sbender9** [comment]
lol. I know, I really f'd that up. I don't know if it worth fixing?
