### ISSUE TITLE
Raymarine (Seatalk) PGN extensions (65288) 

### ISSUE THREAD

**Issue by itemir** [canboat/canboatjs#204]
According to this [Raymarine alarm buzzer manual](https://defender.com/assets/pdf/raymarine/261899_manual.pdf), PGN 65288 seems to support more than what is defined as [Alarm ID enums in pgns.json](https://github.com/canboat/canboat/blob/master/analyzer/pgns.json#L3443). I am not sure how to capture them but it would be good to support these.

**Comment by sbender9** [comment]
They would need to be added to pgn.h in canboat.

**Comment by sbender9** [comment]
cleaning up.. lol
