### ISSUE TITLE
Support for 'standard' length CAN messages

### ISSUE THREAD

**Issue by grazzam** [canboat/canboatjs#220]
I have a REC ABMS that outputs a standard CAN frame (11-bit identifier) instead of the "extended" CAN frame (29-bit identifier) required by NMEA 2000. Is it possible to parse these sentences? Besides finding out what the sentences are from the manufacturer, creating entries in pgns.json, I assume this would also affect the analyzer.

![REC+WS500 candump output](https://user-images.githubusercontent.com/46808200/232629314-c8a2d128-a305-4f5f-a24e-664b5debfcf9.jpg)

**Comment by grazzam** [comment]
Attached image shows a few seconds of the output of "candump can0 | candump2analyzer | analyzer" with these 'standard' length CAN sentences. Seems like analyzer tries to assign new pgns and device IDs based on mis-interpreting the data.

<img width="853" alt="Screenshot 2023-04-17 at 8 20 36 PM" src="https://user-images.githubusercontent.com/46808200/232662786-b5a8c872-8fb0-4cb2-949b-7503f8e1300c.png">

**Comment by sbender9** [comment]
You are using canboat here, not canboatjs. Have you tried with canboatjs?

Otherwise you should open an issue on the canboat git.

**Comment by sbender9** [comment]
And BTW, don't think canboatjs could handle this either.

**Comment by grazzam** [comment]
Ah thanks, agreed I should move this and that although it turns out I have
not tried it with canboatjs, it would likely have similar trouble.
