### ISSUE TITLE
Weird string termination on Raymarine chart plotter when viewing AIS target names

### ISSUE THREAD

**Issue by rmyhren** [canboat/canboatjs#226]
I have a Simrad AI50 that sends AIS data to a RPI4 with a pican-m hat. I then use signal-k to send the AIS-data on the NMEA-2000 bus. Works great, but the strings in the AIS message have some garbled text at the end. Look to me like there is something of in the line termination. Can anybody point me in the direction on how to get this fixed?
![IMG_8160](https://github.com/canboat/canboatjs/assets/2743108/2fb5af78-2a6b-4d50-a051-a8a903ff6491)

**Comment by sbender9** [comment]
Please re-open this issue if it is still a problem.
