### ISSUE TITLE
Add option to configure and run hardware configuration scripts on startup

### ISSUE THREAD

**Issue by navado** [canboat/canboatjs#266]
Some capability to execute configuration scripts on first boot or every startup
- specify scripts to run (in configured order)
- script may be configured as path on disk or pasted as code
- support bash
- ability to test execution from SignalK context (to test permissions, etc), run manually
- backed up as settings
- ability to "skip on restart" marking script to run once per boot

**Comment by sbender9** [comment]
I am sorry, but I think maybe you opened this in the wrong place? There's nothing here that has anything to do with startup..
