### ISSUE TITLE
Use @canboat/pgns package

### ISSUE THREAD

**Issue by webmasterkai** [canboat/canboatjs#35]
I noticed https://www.npmjs.com/package/@canboat/pgns . Should this include it as a dependency instead of maintaining a copy of the json file within the repo?

**Comment by sbender9** [comment]
That change is coming in https://github.com/canboat/canboatjs/pull/28/files

**Comment by webmasterkai** [comment]
Ha! Wish I could make that kind of broad pull request to sk node server ;-)
